### ISSUE TITLE
Impossible to compile because ./waf fails with ValueError: invalid mode: 'rUb'

### ISSUE THREAD

**Issue by hartwork** [Abraca/Abraca#44]
```console
# cd "$(mktemp -d)"

# git clone https://github.com/Abraca/Abraca

# cd Abraca/

# ./waf
Waf: The wscript in '/tmp/tmp.zo0p31WMmM/Abraca' is unreadable
Traceback (most recent call last):
  File "/tmp/tmp.zo0p31WMmM/Abraca/.waf3-1.8.2-d73a7152c626a9df04424e400e8c3d00/waflib/Scripting.py", line 88, in waf_entry_point
    set_main_module(os.path.join(Context.run_dir,Context.WSCRIPT_FILE))
  File "/tmp/tmp.zo0p31WMmM/Abraca/.waf3-1.8.2-d73a7152c626a9df04424e400e8c3d00/waflib/Scripting.py", line 113, in set_main_module
    Context.g_module=Context.load_module(file_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.zo0p31WMmM/Abraca/.waf3-1.8.2-d73a7152c626a9df04424e400e8c3d00/waflib/Context.py", line 324, in load_module
    code=Utils.readf(path,m='rU',encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.zo0p31WMmM/Abraca/.waf3-1.8.2-d73a7152c626a9df04424e400e8c3d00/waflib/Utils.py", line 87, in readf
    f=open(fname,m)
      ^^^^^^^^^^^^^
ValueError: invalid mode: 'rUb'

# python --version
Python 3.11.1
```

**Comment by hartwork** [comment]
@Abraca any thoughts?

**Comment by dsvensson** [comment]
Use an older version of Python. It was probably compiled last time with python 2.x. You could also update waf to a newer version and submit a PR.

**Comment by hartwork** [comment]
@dsvensson with all the fixes from pull request #45 I am now stuck at this:

```console
# VALAC=valac-0.56 ./waf configure --prefix=/usr
# ./waf build -v -k
Waf: Entering directory `[..]/Abraca-fork/build'
[49/57] Processing template: AUTHORS src/resources/ui/abraca-about.ui.in -> build/src/resources/ui/abraca-about.ui
Waf: Leaving directory `[..]/Abraca-fork/build'
Build failed
Traceback (most recent call last):
  File "[..]/Abraca-fork/waftools/about-generator.py", line 59, in _subiter
    self._step()
  File "[..]/Abraca-fork/waftools/about-generator.py", line 49, in _step
    self.current = next(self.it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[..]/Abraca-fork/.waf3-2.1.4-72787ce48f227ac42c4b0da24e780694/waflib/Task.py", line 179, in process
    ret=self.run()
  File "[..]/Abraca-fork/waftools/about-generator.py", line 95, in run
    groups = {group[0]: set(group[2:]) for group in (
  File "[..]/Abraca-fork/waftools/about-generator.py", line 95, in <dictcomp>
    groups = {group[0]: set(group[2:]) for group in (
  File "[..]/Abraca-fork/waftools/about-generator.py", line 96, in <genexpr>
    list(category) for category in split(
RuntimeError: generator raised StopIteration
```
I don't see any clues in there. Any ideas how to continue? Could you take over from here?
